### ISSUE TITLE
Rename each day folder with the format ddd

### ISSUE THREAD

**Issue by AyresMonteiro** [daniphant/100-days-python#2]
The way you are naming it now makes the folders bad-sorted.

![image](https://user-images.githubusercontent.com/53703706/134547898-d89a35c1-977f-494e-aa19-909a6fc24edc.png)

If you use "Day 001" format, folders will be sorted correctly.

**Comment by daniphant** [comment]
Issue has been solved in the PR #3. Thanks for pointing it out :')

PS: As a side note, the naming of folders and files were meant to be done automatically via a Python script that I would make at the end of the course, since my original plan was to keep the repository private until then. The folder structure looked fine on VSCode so I didn't realize the poor formatting when I made the repository public. So yeah, that was the original plan.

**Comment by AyresMonteiro** [comment]
@daniphant It looks good!
